repos:
- repo: local
  hooks:
    - id: isort
      name: isort
      language: python
      types: [python]
      pass_filenames: false
      entry: isort --settings-path=src/api/pyproject.toml src/api/
    - id: black
      name: black
      language: python
      types: [python]
      pass_filenames: false
      entry: black --config=src/api/pyproject.toml src/api/
    - id: flake8
      name: flak8
      language: python
      types: [python]
      pass_filenames: false
      entry: pflake8 --config=src/api/pyproject.toml
    - id: mypy
      name: mypy
      language: python
      types: [python]
      pass_filenames: false
      entry: mypy src/api/ --config-file=src/api/pyproject.toml